version: "3.2"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      node_net:
        ipv4_address: 172.28.1.3

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass empires
    ports:
     - "6379:6379"
    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for containers
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
